'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {World}=require('../web/world.js'),{quiet,rearrange,measure}=require('../web/probe.js');
function tissue(){const w=new World({width:64,height:48,seed:7,agentCount:0});w.gel.fill(.55);return quiet(w);}
test('no preplanted material and no spontaneous signals when charging is disabled',()=>{const w=new World({width:48,height:32,seed:17});assert.equal(w.stats().material,0);w.spontaneous=false;w.step(350);assert.ok(w.stats().material>0);assert.equal(w.stats().peak,0);});
test('seeded runs and saved-state continuations agree exactly',()=>{const a=new World({width:48,height:32,seed:11}),b=new World({width:48,height:32,seed:11});a.step(120);b.step(120);assert.deepEqual(a.snapshot(),b.snapshot());const restored=World.restore(JSON.parse(JSON.stringify(a.snapshot())));a.step(180);restored.step(180);assert.deepEqual(a.snapshot(),restored.snapshot());});
test('strong brush input remains bounded and survives round-trip validation',()=>{const w=tissue();w.brush(22,20,5,'pulse',100);assert.ok(w.stats().peak<=1);World.restore(w.snapshot());});
test('a pulse propagates through tissue, and refractory state can suppress it',()=>{const ready=tissue(),unready=ready.clone(),source={x:20,y:24};unready.recover.fill(.95);const a=measure(ready,source,150),b=measure(unready,source,150);assert.ok(a.reached>50,JSON.stringify(a));assert.ok(b.reached<a.reached*.2,JSON.stringify({a,b}));});
test('an impermeable dam prevents signal crossing',()=>{const w=tissue();for(let y=0;y<w.height;y++)w.brush(32,y,1,'wall');w.brush(18,24,4,'pulse',1.25);w.step(220);let right=0;for(let y=0;y<w.height;y++)for(let x=33;x<w.width;x++)right=Math.max(right,w.excite[y*w.width+x]);assert.equal(right,0);});
test('freeze holds material and carriers exactly while signals evolve',()=>{const w=tissue(),m=w.gel.slice(),x=w.x.slice();w.brush(20,24,4,'pulse');const u=w.excite.slice();w.step(60);assert.deepEqual(w.gel,m);assert.deepEqual(w.x,x);assert.notDeepEqual(w.excite,u);});
test('the signal-write intervention causes persistent material change',()=>{const on=new World({width:40,height:32,seed:8,agentCount:0});on.spontaneous=false;on.gel.fill(.20);on.trail.fill(.7);on.food.fill(.8);on.excite.fill(.6);const off=on.clone();off.writing=false;on.step(1);off.step(1);assert.ok(on.stats().material>off.stats().material);on.clearActivity();off.clearActivity();assert.notDeepEqual(on.gel,off.gel);assert.deepEqual(on.excite,off.excite);});
test('the shuffle preserves gel values, walls and source neighbourhood',()=>{const a=new World({width:48,height:32,seed:3});a.step(300);const b=a.clone(),source={x:24,y:16};rearrange(b,source);assert.deepEqual(Array.from(a.gel).sort(),Array.from(b.gel).sort());for(let i=0;i<a.size;i++)if(Math.hypot(i%48-24,Math.floor(i/48)-16)<=8)assert.equal(a.gel[i],b.gel[i]);assert.deepEqual(a.wall,b.wall);assert.notDeepEqual(a.gel,b.gel);});
test('corrupt snapshots are rejected without replacing a running world',()=>{const w=tissue(),s=w.snapshot();s.gel[10]=NaN;assert.throws(()=>World.restore(s),/Invalid field/);const t=w.snapshot();t.x=[10];assert.throws(()=>World.restore(t),/Invalid field/);});
test('all habitats remain finite in a sustained run',()=>{for(const preset of ['estuary','lace','bloom']){const w=new World({width:72,height:48,seed:23,preset});w.step(1600);World.restore(w.snapshot());assert.ok(w.stats().material>0);assert.ok(w.stats().meanFood>0);}});
